-- Total Sales Per Month
SELECT 
    DATE_TRUNC('month', o.OrderDate) AS Month, 
    SUM(od.Quantity * p.Price) AS TotalSales
FROM Orders o
JOIN OrderDetails od ON o.OrderID = od.OrderID
JOIN Products p ON od.ProductID = p.ProductID
GROUP BY Month
ORDER BY Month;

-- Top-Selling Products
SELECT 
    p.ProductName, 
    SUM(od.Quantity) AS TotalQuantity
FROM OrderDetails od
JOIN Products p ON od.ProductID = p.ProductID
GROUP BY p.ProductName
ORDER BY TotalQuantity DESC
LIMIT 5;

-- Sales by Customer
SELECT 
    c.CustomerName, 
    SUM(od.Quantity * p.Price) AS TotalSales
FROM Orders o
JOIN Customers c ON o.CustomerID = c.CustomerID
JOIN OrderDetails od ON o.OrderID = od.OrderID
JOIN Products p ON od.ProductID = p.ProductID
GROUP BY c.CustomerName
ORDER BY TotalSales DESC;

-- Orders Handled by Each Employee
SELECT 
    e.FirstName || ' ' || e.LastName AS EmployeeName, 
    COUNT(o.OrderID) AS NumberOfOrders
FROM Orders o
JOIN Employees e ON o.EmployeeID = e.EmployeeID
GROUP BY EmployeeName
ORDER BY NumberOfOrders DESC;

-- Revenue Generated by Each Employee
SELECT 
    e.FirstName || ' ' || e.LastName AS EmployeeName, 
    SUM(od.Quantity * p.Price) AS TotalRevenue
FROM Orders o
JOIN OrderDetails od ON o.OrderID = od.OrderID
JOIN Products p ON od.ProductID = p.ProductID
JOIN Employees e ON o.EmployeeID = e.EmployeeID
GROUP BY EmployeeName
ORDER BY TotalRevenue DESC;

